### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by TheShadowOfHassen** [Lemente/cave_painting#1]
It may be just me. I look a lot at other people's code and see how/what they are doing. Personally, I like more open code like MIT or Lesser GPL instead of GNU GENERAL because I like to be able to use it in a game that isn't always GNU GENERAL, however what I think is even worse is no license at all because I don't know what I can do with it and I hate pirating/doing things with people's stuff that I'm not supposed to.

**Comment by Lemente** [comment]
hey, I forgot to add one, sorry!
this mod is based on this example by @grorp https://github.com/grorp/ggraffiti/issues/9
they shared it under CC0, so I'll do the same, even though it might be a bit impractical.
Though I believe I can multilicense code, so consider my contribution to this mod under CC0 license, the MIT license, as well as LGPL-3.0-or-later license.

**Comment by Lemente** [comment]
done!
Tell me if there is anything missing
